name: Backend Build and Release

on:
  push:
    branches: [ master ]
    
jobs:

  test-build-publish:
    name: Run Tests, Build, Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Commit Code
      uses: actions/checkout@v2
    - name: Run Unit Tests
      run: ./backend/run-tests.sh
    - name: Build Container
      run: ./backend/make-container.sh
    - name: Tag Image for Dev Publish
      run: |
        docker tag crossword-app-server:local-build rbrajcich/crossword-app-server-dev:job-$GITHUB_RUN_ID
        echo "Tagged as rbrajcich/crossword-app-server-dev:job-${GITHUB_RUN_ID}"
    - name: Push Image to Docker Hub
      run: |
        echo $DOCKERHUB_TOKEN | docker login -u rbrajcich --password-stdin
        docker push rbrajcich/crossword-app-server-dev
