name: Test, Build, Release

on:
  push:
    branches: [ master ]
    
jobs:

  backend-test-build-publish:
    name: Run Backend Tests, Build, Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Commit Code
      uses: actions/checkout@v2
    - name: Run Unit Tests
      run: ./backend/run-tests.sh
    - name: Build Container
      run: ./backend/make-container.sh
    - name: Tag Dev Image with Job Run Id
      run: |
        docker tag crossword-app-server:local-build rbrajcich/crossword-app-server-dev:job-$GITHUB_RUN_ID
        echo "Tagged as rbrajcich/crossword-app-server-dev:job-${GITHUB_RUN_ID}"
    - name: Publish Image to Docker Hub Dev Repo
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo $DOCKERHUB_TOKEN | docker login -u rbrajcich --password-stdin
        docker push rbrajcich/crossword-app-server-dev

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: backend-test-build-publish
    steps:
    - name: Checkout Commit Code
      uses: actions/checkout@v2
    - name: Pull Built Backend Container
      run: docker pull rbrajcich/crossword-app-server-dev:job-$GITHUB_RUN_ID
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install semantic-release and Plugins
      run: |
        npm install -g semantic-release@17
        npm install -g @semantic-release/exec@5
    - name: Release with semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: npx semantic-release
